### ISSUE TITLE
No valid wecker.yml found.

### ISSUE THREAD

**Issue by luebken** [giantswarm/swarm-wercker#2]
I was walking through the guide and got a warning at the last step: 

> Setup your wercker.yml We're unable to setup the environment for your repository. Is your wercker.yml valid? check again

I've than read in the guide: 

> Regardless of whether Wercker finds a valid wercker.yml

Why is this the case? Can we fix this?

**Comment by luebken** [comment]
ping @kordless

**Comment by kordless** [comment]
The instructions for the guide address this issue. I would suggest opening an issue with Wercker given it's their UI and the wercker.yml file does actually work as expected, besides getting the warning.

**Comment by kordless** [comment]
This appears to be caused by the fact enviroment variables exist in the wercker.yml file which cannot be populated at create time because the variables are pulled from the deploy configuration, which doesn't exist during creation. This is definitely a Wercker issue.
