### ISSUE TITLE
Rename build step

### ISSUE THREAD

**Issue by luebken** [giantswarm/swarm-wercker#3]
What is the scheme to name build steps? Here it says `- kordless/giantswarm:`
https://github.com/giantswarm/swarm-wercker/blob/master/wercker.yml#L36
But it should probably named differently.

Edit: It's probably because it's build by @kordless and deployed as a custom build step. Still we should update it. If necessary with a giantswarm user.

**Comment by kordless** [comment]
This should be opened on https://github.com/giantswarm/giantswarm-wercker-step, not this repo. Regardless, making a custom Github and Wercker account named 'giantswarm' is complicating matters for little gain, IMHO.
