### ISSUE TITLE
Use the API and not the CLI

### ISSUE THREAD

**Issue by luebken** [giantswarm/swarm-wercker#4]
I can't figure out how exactly the build step is implemented but it seems its to use the CLI. The problem I encountered is that the swarm cli prints out that it needs to be update it. Question is how the build step is implemented and wether can switch to the API.

**Comment by kordless** [comment]
The step is located here: https://github.com/giantswarm/giantswarm-wercker-step. The CLI needs to have a version bump done on it in the step, but the ticket for that doesn't belong here.
